# Libraries for Data Science

As mentioned before, python is a general purpose programming language.
What allowed python to become a favorite of data scientists, is the support of community developed libraries.
In this chapter, we will discuss introduce a some of these libraries.

## `numpy` 

The library `numpy` allows python to perform vectorized calculations and matrix operations.
It offers advanced features beyond the capabilities of built-in python lists and tuples.
It also provides a library of mathematical functions, random number generators, etc.
Compared to builtin functions, python is able to perform efficient calculations by leveraging C code.

### `ndarray`

NumPy relies on its own compound class called `ndarray` (which stands for n-dimensional array, sometimes also referred to as `array`). 
Here's a simple one-dimensional array, created using the constructor `array()`

In [1]:
import numpy as np

np.array([0, 1, 2, 3])

array([0, 1, 2, 3])

You can create multidimensional arrays by providing the constructor with a list of list of numbers:

In [2]:
mat = np.array([[1,2,3],[4,5,6]])
mat

array([[1, 2, 3],
       [4, 5, 6]])

These `array` class comes with useful attributes such as:

- `shape` which represents the dimensions of the array
- `ndim` which represents the number of dimensions of the array 
- `dtype` which represents the datatype of the array's elements
- `size` which represents the number of elements in the array.

In [3]:
mat.shape

(2, 3)

In [4]:
mat.ndim

2

In [5]:
mat.dtype.name #use the dtype.name to show the string representation of the datatype

'int64'

In [6]:
mat.size

6

You can also create a NumPy array using other useful constructors:

In [7]:
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.arange(5, 20, 0.5)

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ,
       10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

When using arithmetic operations (`+`, `*`, `-`, `/`) on NumPy arrays, the operations are treated as element wise operations.

### NumPy Broadcasting

You can use these operations on any pair of arrays with compatible shapes.
Shape compatibility in NumPy works with respect to the NumPy broadcasting rules.
NumPy first compares number of dimensions, if the two operands have unequal dimensions, NumPy implicitly adds dimensions of size one to the left of the lower-dimensional operand.
For example, when attempting to perform operations on a pair of arrays with the shapes: $3 \times 4 \times 5$, and $5$, the second array is converted to a $1 \times 1 \times 5$ array.

With the number of dimensions settled, numpy checks if each dimension has compatible sizes.
Sizes are compatible if they are equal or one of the sizes is exactly one.
If a dimension is exactly one, the array is "stretched" to accommodate the larger array.

For example, given:

In [10]:
A = np.arange(1,61).reshape((3,4,5)) # reshape is a method used change the dimensions of the array
B = np.array([1,2,3,4,5])

Since `B` has two dimensions, it is implicitly reshaped into a $1 \times 1 \times 5$ array.
Based on the broadcasting rules `A` and `B` of compatible sizes.
To accommodate the elements of `A`, the elements of `B` are stretched to a goal shape of $3 \times 4 \times 5$.
First, it is stretched into a $4 \times 5$ array by copying itself four times, similar to the following operation:

In [11]:
twoDimensions = np.array([B] * 4) # stretches using list multiplication
twoDimensions

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

The resulting array is then stretched 3 times to reach the goal shape $3 \times 4 \times 5$:

In [12]:
threeDimensions = np.array([twoDimensions] * 3)
threeDimensions

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

With the sizes now matching it applies the calculation.
You can compare the calculations indeed match:

In [13]:
print(A * B) # automatic broadcasting
print(A * threeDimensions) # explicit stretching

[[[  1   4   9  16  25]
  [  6  14  24  36  50]
  [ 11  24  39  56  75]
  [ 16  34  54  76 100]]

 [[ 21  44  69  96 125]
  [ 26  54  84 116 150]
  [ 31  64  99 136 175]
  [ 36  74 114 156 200]]

 [[ 41  84 129 176 225]
  [ 46  94 144 196 250]
  [ 51 104 159 216 275]
  [ 56 114 174 236 300]]]
[[[  1   4   9  16  25]
  [  6  14  24  36  50]
  [ 11  24  39  56  75]
  [ 16  34  54  76 100]]

 [[ 21  44  69  96 125]
  [ 26  54  84 116 150]
  [ 31  64  99 136 175]
  [ 36  74 114 156 200]]

 [[ 41  84 129 176 225]
  [ 46  94 144 196 250]
  [ 51 104 159 216 275]
  [ 56 114 174 236 300]]]


Here's another example involving an array of size $4$ and an array of size $5 \times 1$:

In [14]:
C = np.array([1,2,3,4])
D = np.array([1,2,3,4,5]).reshape((5,1))

To accommodate each other, both arrays are stretched into $4 \times 5$:

In [15]:
stretchedC = np.array([C] * 5)
stretchedD = np.repeat(D, 4, axis = 1) # stretches the column into 5 columns

print(stretchedC * stretchedD)
print(C * D)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]
 [ 5 10 15 20]]
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]
 [ 5 10 15 20]]


NumPy also features mathematical functions that can be applied to scalar values or arrays.
When applied to arrays these functions are applied element-wise.

In [16]:
arr = np.arange(0,10,0.1)
print(np.sqrt(arr))
print(np.round(arr,10))
print(np.ceil(arr))

[0.         0.31622777 0.4472136  0.54772256 0.63245553 0.70710678
 0.77459667 0.83666003 0.89442719 0.9486833  1.         1.04880885
 1.09544512 1.14017543 1.18321596 1.22474487 1.26491106 1.30384048
 1.34164079 1.37840488 1.41421356 1.44913767 1.4832397  1.51657509
 1.54919334 1.58113883 1.61245155 1.64316767 1.67332005 1.70293864
 1.73205081 1.76068169 1.78885438 1.81659021 1.84390889 1.87082869
 1.8973666  1.92353841 1.94935887 1.97484177 2.         2.02484567
 2.04939015 2.07364414 2.0976177  2.12132034 2.14476106 2.16794834
 2.19089023 2.21359436 2.23606798 2.25831796 2.28035085 2.30217289
 2.32379001 2.34520788 2.36643191 2.38746728 2.40831892 2.42899156
 2.44948974 2.46981781 2.48997992 2.50998008 2.52982213 2.54950976
 2.56904652 2.58843582 2.60768096 2.62678511 2.64575131 2.66458252
 2.68328157 2.70185122 2.7202941  2.73861279 2.75680975 2.77488739
 2.79284801 2.81069386 2.82842712 2.84604989 2.86356421 2.88097206
 2.89827535 2.91547595 2.93257566 2.94957624 2.96647939 2.9832

Arrays in NumPy also support advanced indexing, including slicing, logical indexing, and iteration:

In [17]:
arr = np.arange(0,20)
print(arr[10:15])
print(arr[3:12:2])
print(arr[:5:-2])
print(arr[arr % 2 == 0])

[10 11 12 13 14]
[ 3  5  7  9 11]
[19 17 15 13 11  9  7]
[ 0  2  4  6  8 10 12 14 16 18]
